- hosts: work
  connection: docker
  tasks:
    - apt: name={{ item }}
      with_items:
        - locales
    - debconf: name=locales question='locales/locales_to_be_generated' value='ja_JP.UTF-8 UTF-8' vtype='multiselect'
      notify: locale-gen
    - apt: name={{ item }}
      with_items:
        - netbase
        - whois
        - git
        - vim
        - man-db
    - get_url: url=https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
        dest=/tmp/go1.6.2.linux-amd64.tar.gz
        checksum=sha256:e40c36ae71756198478624ed1bb4ce17597b3c19d243f3f0899bb5740d56212a
      register: golang
    - unarchive: src=/tmp/go1.6.2.linux-amd64.tar.gz dest=/usr/local copy=no
      when: golang.changed
  handlers:
    - name: locale-gen
      script: /var/lib/dpkg/info/locales.postinst configure
