- hosts: localhost
  connection: local

  roles:
    - docker-compose

  tasks:
    - name: install screen
      apt: name=screen

    - name: install ipcalc
      apt: name=ipcalc

    - name: install dnsutils
      apt: name=dnsutils
